### ISSUE TITLE
Problem with options

### ISSUE THREAD

**Issue by gbesacier** [linuxgurugamer/ksp-KerbalLaunchFailure#13]
There seemed to be a problem with how the mod options are processed or saved. I think it explains both why on a new install all the options are at 0 instead of the documented defaults (2% failure chance, failures stop at 65% of atmosphere altitude, etc.) and why people report that they have a failure every single launch. In the save file, we have this:

		KLFCustomParams
		{
			initialFailureProbability = 2
			expPartFailureProbability = 10
			maxFailureAltitudePercentage = 65
			failurePropagateProbability = 70
			delayBetweenPartFailures = 0.15
			enabled = True
			initialFailureProb = 0.02
			expPartFailureProb = 0.1
			maxFailureAltitudePerc = 0.65
			highlightFailingPart = True
			propagationChanceDecreases = False
			failurePropagateProb = 0.7
			delayBetweenPartFail = 0.0015
			minTimeBeforeFailure = 5
			maxTimeBeforeFailure = 300
		}

It seems changing the options in-game changes initialFailureProb in the save file, but it seems the actual mod logic uses initialFailureProbability (e.g. Failure.cs line 661). Same thing with other parameters.

**Comment by linuxgurugamer** [comment]
Thanks, I'll take a look at it and fix it.
Appreciate the heads up

**Comment by linuxgurugamer** [comment]
Fixed thanks to a forum user, this was caused by having to program around a KSP bug
