### ISSUE TITLE
Latest download contains wrong mod

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/ksp-KerbalLaunchFailure#17]
The latest download for KerbalLaunchFailure on SpaceDock:

https://spacedock.info/mod/989/Kerbal%20Launch%20Failure/download/1.1.2.4

... contains Kartographer instead:

![image](https://user-images.githubusercontent.com/1559108/50983087-8e18a180-14f6-11e9-8a56-8a5e56cf98a2.png)

**Comment by linuxgurugamer** [comment]
I just replaced the file on spacedock with the correct one, can you verify the meta data is good?
Thanks

**Comment by HebaruSan** [comment]
Confirmed fixed, thanks.
